package app

import "strings"

func buildRenderHelpText() string {
	return strings.Join([]string{
		"MEZZOTONE HELP",
		"",
		"Controls",
		"",
		"Global",
		"  h              Toggle help",
		"  esc            Back / Close help / Quit ",
		"  ctrl+c         Quit",
		"",
		"File Picker",
		"  j/k or up/down Navigate options",
		"  pgdown         Go To Bottom",
		"  pgup           Go To Top",
		"  enter/right    Open directory or select image",
		"  left/backspace Go back directory",
		"",
		"Render Options",
		"  j/k or up/down Navigate options",
		"  pgdown         Go To Bottom",
		"  pgup           Go To Top",
		"  enter          Edit numeric fields / change enum / confirm",
		"  space          Toggle bool values",
		"  left/right     Change enum values",
		"  esc            Cancel edit or go back to file picker",
		"",
		"Render View",
		"  arrows         Scroll output/help",
		"  h              Hide help",
		"  f              Toggle Fullscreen",
		"  pgdown         Go To Bottom",
		"  pgup           Go To Top",
		"  shift+up       Go To Bottom",
		"  shift+down     Go To Top",
		"  shift+left     Go To Left",
		"  shift+right    Go To Right",
		"  c              Copy to clipboard",
		"  t              Export to txt",
		"  i              Export to image",
		"  g              Export to gif",
		"  v              Export to video",
		"",
		"Render Option Explanations",
		"",
		"Text Size",
		"  Character cell width in pixels. Larger values reduce detail.",
		"",
		"Font Aspect",
		"  Character height ratio vs width to match terminal font shape.",
		"",
		"Directional Render",
		"  Uses edge direction to place oriented glyphs on strong edges.",
		"",
		"Edge Threshold",
		"  Edge cutoff (0..1) for directional glyph replacement.",
		"",
		"Reverse Chars",
		"  Inverts ramp mapping for terminals/themes where output looks",
		"  visually inverted with default ramp direction.",
		"",
		"High Contrast",
		"  Applies stronger luminance contrast before glyph mapping.",
		"",
		"Rune Mode",
		"  Ramp preset: ASCII, UNICODE, DOTS, RECTANGLES, BARS.",
	}, "\n")
}
